# Machine settings
host_name: megacorp-node
server_admin_email: webmaster@theteam.co.uk

# Project settings
client_name: megacorp
project_name: megacorp-wall

domains:
    production: example.com
    staging: example.staging.theteamdigital.com

# Django project settings
python_project_name: example
static_url : static/
media_url: attachments/
